name: Deployment-Reuseable workflow with inputs and outps

# For dev-deploy and prod-deploy we are creating Reusable-workflow

on: 
   workflow_call: 
    inputs:
      mongodb-uri:
        required: true
        type: string
      kubectl-version:
         description: Provide the required kubectl version
         default: v1.27.0
         required: false
         type: string
         # it will default to v1.27.0 if we not provide any value in caller file that is  PR.yaml file
      k8s-manifest-dir:
        description: Directory containing  manifests files
        default: kubernetes/
        required: true
        type:  string
      environment:
        description: provide the deploymet environment
        default:  dev
        required:  true
        type: string 
        
        # some secrets are not propagated from caller workflow to called that why
       # we use inputs to propagate them 
       
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true
    outputs:
      application-url:
        value: ${{jobs.reuse-deploy.outputs.APP_INGRESS_URL}}
   
jobs:
  reuse-deploy:
      environment: 
        name: ${{ inputs.environment}}
        url:  https://${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        # url is noting but app that we are deploying in kubernetes so the output can be displayed and sov that reiewers can view 
      outputs:
          APP_INGRESS_URL : ${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
          
      runs-on: ubuntu-latest
      steps:
          - name: checkout Repo
            uses: action/checkout@v4
            # checout the repo where the manifest files exists
          - name: Install kubectl Cli
            uses: azure/setup-kubectl@v3
            # installing kubectl cli using action
            with:
              version: '${{inputs.kubectl-version}}'
              # Here we are providing KUBECONFIG FILE in order for kubectl to connet with it run commands
          - name: Set Kubeconfig file
            uses: azure/k8s-set-context@v3
            with:
              method: false
              kubeconfig: ${{ secrets.k8s-kubeconfig}} # here we placed our config file in secrets of repository that why
              context: kind-kind
          - name: Fetch kubernets Cluster Details
            run: | 
              kubectl version --short
              echo -----------------------------------------
              kubectl get nodes
              
     ## This is will fail becasue we have not provided the KUBECONFIG file in order for kubectl cli to communicate with cluster and work with it
     ## Hera we are adding kubeconfig file as secret to github
          - name: Save Nginx ingress Controller Ip as a GITHUB Environment variable
            run: | 
              echo "INGRESS_IP=${kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadbalancer.ingress[0].ip}"}" >> $GITHUB_ENV
              # Here we are going to create Environment variable in the workflow and use it across the steps or multiple jobs  we are using action called  $GITHUB_ENV to set env variable
              # we can access this using ${{env.INGRESS_IP}} we are env because by above action we set env variables 
          - name: replace Token inn manifest file
            uses: cschleiden/replace-tokens@v1
            with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["${{ inputs.k8s-manifest-dir}}*.yaml"]' # location where you want repalce these Token # Here the location is kubernetes/development where our manifests file Exists
            env:
              NAMESPACE: ${{vars.NAMESPACE}}
              REPLICAS: ${{vars.REPLICAS}}
              IMAGE: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
              INGRESS_IP: ${{env.INGRESS_IP}}
    
          - name: check files
            run: |
              cat ${{ inputs.k8s-manifest-dir}}*.yaml
              
        # To check we corectly replaced the Tokens in kubernets manifest files which are in the path  kubernetes/development/*.yaml
        # but deployment will fail because  we are using secretRef in deployment.yaml file
        # so we need to create secret before we deploy in cluster
        # because our docker file  using env  so we create  secrets such as to pass values
        # ENV MONGO_URI=uriPlaceholder
        #  ENV MONGO_USERNAME=usernamePlaceholder
       # ENV MONGO_PASSWORD=passwordPlaceholder
          - name: Create MongoDB secret
            run: | 
              kubectl  -n {{vars.NAMESPACE}} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI=${{inputs.mongodb-uri}} \
              --from-literal=MONGO_USERNAME=${{vars.MONGO_USERNAME}} \
              --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password}} |
              --save-config \
              --dry-run=client \
              -o yaml | kubectl apply -f -
            # mongo-db-creds this is name that we used on deployment file as secret name
    
          # it will apply all files to deploy
          - name: Deploy to Dev Env
            run: |
              kubectl apply -f ${{ inputs.k8s-manifest-dir}}
          - name: Set App Ingress Host URL
            id: set-ingress-host-address
            run: | 
              echo "APP_INGRESS_HOST=$(kbuectl -n ${{ vars.NAMESPACE}}) get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"
              
          # we are using GITHUBENV to pass variable to next steps
          # but we want to pass between two jobs we have to use job output from one job and reference in another job   
       
           
           
           
           
           
           
           
           
           
           
           
           
           