name: Unit Test Job

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    
    # i tried to create a mongodb service but it was not working

    # services:
    #   mongodb:
    #     image: mongo:6.0
    #     ports:
    #       - 27017:27017
    #     options: >-
    #       --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
    #       --health-interval 10s
    #       --health-timeout 5s 
    #       --health-retries 5
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: example

    env:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_URI: "mongodb+srv://root:example@cluster0.97ofrph.mongodb.net/test?retryWrites=true&w=majority


    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v3
        with:
          node-version: 20
      

      - name: Install Dependencies
        run: npm install

      # Wait for MongoDB to be ready

      - name: Unit Testing
        run: npm test
        
        
        


      # - name: Upload Test Results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: test-results.xml
      
      
      - name: Upload Code Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage